### PR TITLE
Updated auto and endgame pages

### PR DESCRIPTION
**Pull request by gregk27**
Updated the auto (now pregame) and endgame (now postgame) pages

### CODE REVIEW

**Comment by ajayyy** [comment]
Does this conflict with Xan's work? I'll look over it when I'm home.

**Comment by gregk27** [comment]
Ooh it might i'll check

**Comment by gregk27** [comment]
Because I renamed autopage in my changes, the conflicts should be easy to fix

**Comment by ajayyy** [comment]
It might be best to push commits into Xan's fork, just to keep all the
changes out of master for now until it is complete, that's what I have been
doing so far.

**Comment by ajayyy** [comment]
No, but he redid the auto page and end game page to fit with this year as
well.

**Comment by gregk27** [comment]
Ya, a test pull had overly complex conflicts, so i'll wait until his is merged then resolve

**Comment by ajayyy** [comment]
Did you do anything other than renaming?

**Comment by gregk27** [comment]
Changes to endgamepage, some changes to mainactivity, and edits to the pregamepage

**Comment by gregk27** [comment]
I'll close this until the conflicts are resolved.

**Comment by ajayyy** [comment]
Ok, I'll talk about it with you Monday.

**Comment by ajayyy** [comment]
Ok, I looked through the pull request properly this time. Other than the rename, the additions have already been done in Xan's pull request as far as I can tell, so I think it would be easier to just create a separate pull request with the rename. The UI in Xan's fork is still not final and I have some planned tweaks.

**Review by ajayyy — COMMENTED** [review]
Ok, I looked through the pull request properly this time. Other than the rename, the additions have already been done in Xan's pull request as far as I can tell, so I think it would be easier to just create a separate pull request with the rename. The UI in Xan's fork is still not final and I have some planned tweaks.

**Pull request closed without merging**
