### PR TITLE
Merge

### PR DESCRIPTION
**Pull request by gregk27**
Implemented recursive saving code

Started work on new layouts. 
 - App is set to landscape
 - Phone size auto page done

### CODE REVIEW

**Comment by ajayyy** [comment]
Merge conflicts yay

**Comment by gbuckholtz** [comment]
windiff is your friend

**Comment by gbuckholtz** [comment]
hmm.  I did a merge locally with pr24 and master and there weren't problems

**Comment by ajayyy** [comment]
I think it's just the fact that one of the commits was accidentally committed to master and the fork, will fix it now.

**Comment by ajayyy** [comment]
Turns out merge commits were disabled and only rebase and merge was enabled

**Pull request merged**
