### PR TITLE
Added qualitative page (Merge after other request)

### PR DESCRIPTION
**Pull request by gregk27**
Added qualitative page

### CODE REVIEW

**Comment by ajayyy** [comment]
Ooh, I like the idea of splitting the post game page. We should move over the rating bars as well.

**Comment by gregk27** [comment]
That was the plan

**Comment by gregk27** [comment]
so endgame is JUST endgame

**Comment by gregk27** [comment]
and i've got my code merged w/ xan's, so when that gets accepted I can merge across the changes

**Comment by gregk27** [comment]
These changes are now requested into xan/master

**Comment by ajayyy** [comment]
Ok sweet, I'll check that out

**Comment by ajayyy** [comment]
https://github.com/x3a1n4/LakeEffectScoutingApp/pull/2

**Pull request closed without merging**
